import { Task } from "./types/public-types";

export function initTasks() {
  // const currentDate = new Date();
  // const tasks: Task[] = [
  //   {
  //     start: new Date(2024, 3, 21),
  //     start: new Date(2024, 3, 21),
  //     end: new Date(2024, 3, 27),
  //     name: "R-032",
  //     projectName: "R-032",
  //     id: "ProjectSample",
  //     progress: 90,
  //     score: 0,
  //     comment: "",
  //     type: "project",
  //     status: "removal",
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-01",
  //     camera: 212,
  //     typeProject: "Removal C",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 100,
  //     checkerProgress: 80,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     hideChildren: false,
  //     displayOrder: 1,
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 3, 21),
  //     end: new Date(2024, 3, 24),
  //     name: "Merge",
  //     projectName: "R-032",
  //     id: "0",
  //     progress: 100,
  //     score: 0,
  //     comment: "",
  //     type: "task",
  //     status: "waitingDelivery",
  //     project: "ProjectSample",
  //     displayOrder: 2,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-01",
  //     camera: 212,
  //     typeProject: "Merge",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     workerProgrees: 100,
  //     checkerProgress: 100,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 3, 24),
  //     end: new Date(2024, 3, 27),
  //     name: "Removal C",
  //     projectName: "R-032",
  //     id: "1",
  //     progress: 80,
  //     score: 0,
  //     comment: "",
  //     status: "onHold",
  //     type: "task",
  //     project: "ProjectSample",
  //     displayOrder: 3,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-01",
  //     camera: 212,
  //     typeProject: "Removal C",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 50,
  //     checkerProgress: 0,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },    
  //   {
  //     start: new Date(2024, 3, 27),
  //     end: new Date(2024, 4, 2),
  //     name: "R-033",
  //     projectName: "R-033",
  //     id: "ProjectSample1",
  //     progress: 90,
  //     score: 0,
  //     comment: "",
  //     type: "project",
  //     status: "waitingDelivery",
  //     hideChildren: false,
  //     displayOrder: 4,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-02",
  //     camera: 252,
  //     typeProject: "Removal C",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 90,
  //     checkerProgress: 0,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 3, 27),
  //     end: new Date(2024, 4, 2),
  //     name: "Removal C",
  //     projectName: "R-033",
  //     id: "3",
  //     progress: 100,
  //     score: 0,
  //     comment: "",
  //     status: "",
  //     type: "task",
  //     project: "ProjectSample1",
  //     displayOrder: 5,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-02",
  //     camera: 252,
  //     typeProject: "Removal C",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 90,
  //     checkerProgress: 0,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 4, 2),
  //     end: new Date(2024, 4, 9),
  //     name: "R-034",
  //     projectName: "R-034",
  //     id: "ProjectSample2",
  //     progress: 25,
  //     score: 0,
  //     comment: "",
  //     type: "project",
  //     status: "removal",
  //     hideChildren: false,
  //     displayOrder: 6,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-03",
  //     camera: 353,
  //     typeProject: "Removal A",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 25,
  //     checkerProgress: 0,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 4, 2),
  //     end: new Date(2024, 4, 9),
  //     name: "Merge",
  //     projectName: "R-034",
  //     id: "4",
  //     progress: 25,
  //     score: 0,
  //     comment: "",
  //     status: "",
  //     type: "task",
  //     project: "ProjectSample2",
  //     displayOrder: 7,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-03",
  //     camera: 353,
  //     typeProject: "Removal A",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 25,
  //     checkerProgress: 0,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 4, 9),
  //     end: new Date(2024, 4, 20),
  //     name: "R-035",
  //     projectName: "R-035",
  //     id: "ProjectSample3",
  //     progress: 0,
  //     score: 0,
  //     comment: "",
  //     type: "project",
  //     status: "notStart",
  //     hideChildren: false,
  //     displayOrder: 8,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-04",
  //     camera: 123,
  //     typeProject: "Removal B",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 0,
  //     checkerProgress: 0,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 4, 9),
  //     end: new Date(2024, 4, 20),
  //     name: "Removal C",
  //     projectName: "R-035",
  //     id: "5",
  //     progress: 0,
  //     score: 0,
  //     comment: "",
  //     status: "",
  //     type: "task",
  //     project: "ProjectSample3",
  //     displayOrder: 9,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-04",
  //     camera: 123,
  //     typeProject: "Removal B",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "",
  //     workerProgrees: 0,
  //     checkerProgress: 0,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 3, 1),
  //     end: new Date(2024, 3, 12),
  //     name: "R-037",
  //     projectName: "R-037",
  //     id: "ProjectSample5",
  //     progress: 100,
  //     score: 95,
  //     comment: "goods",
  //     type: "project",
  //     status: "complete",
  //     hideChildren: false,
  //     displayOrder: 11,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-05",
  //     camera: 350,
  //     typeProject: "Removal C",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     workerProgrees: 100,
  //     checkerProgress: 100,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 3, 1),
  //     end: new Date(2024, 3, 12),
  //     name: "Removal C",
  //     projectName: "R-037",
  //     id: "Task 7",
  //     progress: 100,
  //     score: 0,
  //     comment: "goods",
  //     status: "",
  //     type: "task",
  //     project: "ProjectSample5",
  //     displayOrder: 12,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",   
  //     mainProjectName: "2900317/Customer-01/Business-05",
  //     camera: 350,
  //     typeProject: "Removal C",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     workerProgrees: 100,
  //     checkerProgress: 100,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  //   {
  //     start: new Date(2024, 3, 1),
  //     end: new Date(2024, 3, 12),
  //     name: "R-038",
  //     projectName: "R-038",
  //     id: "ProjectSample6",
  //     progress: 100,
  //     score: 0,
  //     comment: "Goold",
  //     type: "project",
  //     status: "complete",
  //     hideChildren: false,
  //     displayOrder: 13,
  //     checkerImage:"300-1.jpg",
  //     workerImage:"300-2.jpg",
  //     mainProjectName: "2900317/Customer-01/Business-06",
  //     camera: 250,
  //     typeProject: "Removal C",
  //     termsOfRequestJP: "Japanese language",
  //     termsOfRequestEN: "Japanese language translation into English",
  //     characteristicsJP: "Japanese language",
  //     characteristicsEN: "Japanese language translation into English",
  //     dataLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     uploadLink: "https://drive.google.com/file/d/1raWjarmqENUcG7vvClmvjchlfOKUkpbQ/view?usp=drive_link",
  //     workerProgrees: 100,
  //     checkerProgress: 100,
  //     workerName: "Binly",
  //     checkName: "Aye",
  //     styles: { progressColor: '#4E8BC4', progressSelectedColor: '#8BB4D2' },
  //   },
  // ];
  // return tasks;
}


export function getStartEndDateForProject(tasks: Task[], projectId: string) {
  const projectTasks = tasks.filter(t => t.project === projectId);
  let start = projectTasks[0].start;
  let end = projectTasks[0].end;

  for (let i = 0; i < projectTasks.length; i++) {
    const task = projectTasks[i];
    if (start.getTime() > task.start.getTime()) {
      start = task.start;
    }
    if (end.getTime() < task.end.getTime()) {
      end = task.end;
    }
  }
  return [start, end];
}
